<?php

namespace app\controllers;

use yii\filters\AccessControl;
use yii\web\Controller;

class BotCoreController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                //'only' => ['logout'],
                'rules' => [
                    [
                        'allow' => true,
                        //'actions' => ['login', 'signup'],
                        //'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        //'actions' => ['login','signup','logout','about','index','contact' ],
                        //'roles' => ['?'],
                    ],
                ],

            ],
        ];
    }

    public function beforeAction($action)
    {
        // To bypass from FB bot
        $this->enableCsrfValidation = false;

        // To get original post data from FB bot
        //$this->post_orig_data = Yii::$app->request->getRawBody();
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        echo "Hi, I'm BTC bot";
    }
    public static function processIntent($intent = false) {

        // $intent->result->fulfillment->speech;
        // $intent->result->action

        if ($intent->result->action == 'btc_rate') {
            return ['type' => 'text', 'msg' => 'BTC to USD rate now: ' . ExchangeController::getBtcToUsdRate() . ' USD'];
        } else {
            return ['type' => 'text', 'msg' => $intent->result->fulfillment->speech];
        }

    }


}
