<?php

namespace app\controllers;

use app\commands\MarketDataController;
use app\models\MarketData;
use yii\filters\AccessControl;
use yii\httpclient\Client;
use yii\web\Controller;

class ExchangeController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                //'only' => ['logout'],
                'rules' => [
                    [
                        'allow' => true,
                        //'actions' => ['login', 'signup'],
                        //'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        //'actions' => ['login','signup','logout','about','index','contact' ],
                        //'roles' => ['?'],
                    ],
                ],

            ],
        ];
    }

    public function beforeAction($action)
    {

        // To bypass from FB bot
        $this->enableCsrfValidation = false;

        // To get original post data from FB bot
        //$this->post_orig_data = Yii::$app->request->getRawBody();

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        echo "Hi, I'm BTC bot";
    }
    public static function getMarketPrice($exchange_id = 'blockchain.info', $market_id = 'BTC_USD') {

        if ($market_id == 'BTC_USD') {

            $client = new Client();
            $response = $client->createRequest()
                ->setMethod('GET')
                ->setUrl('https://blockchain.info/en/ticker')
                ->send();
            if ($response->isOk) {

                return round($response->data['USD']['buy'], 2);

            }

        }

        //---

        if ($market_id == 'ETH_USD') {

            // ETH USD
            $client = new Client();
            $response = $client->createRequest()
                ->setMethod('GET')
                ->setUrl('https://api.coinmarketcap.com/v1/ticker/ethereum/')
                ->send();
            if ($response->isOk) {

                return round($response->data[0]['price_usd'], 2);

            }

        }

    }

}
